project:
  type: website

website:
  title: "Mortality Clustering Project"
  open-graph: true
  page-footer: "Maintained with ❤️ by Ronak and Quarto"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  search: 
    location: sidebar
    type: textbox
  navbar:
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Full Datadicts
        menu:
        - text: Afghanistan DHS Dictionary
          href: dadict_afdhs.qmd
        - text: Bangladesh DHS Dictionary
          href: dadict_bddhs.qmd
        - text: India DHS Dictionary
          href: dadict_iadhs.qmd  
        - text: Maldives DHS Dictionary
          href: dadict_mvdhs.qmd
        - text: Nepal DHS Dictionary
          href: dadict_npdhs.qmd
        - text: Pakistan DHS Dictionary
          href: dadict_pkdhs.qmd
      - text: Variable Checklist
        href: davars_checklist.qmd
      - text: Datapool Pre-checks
        menu:
        - text: Afghanistan DHS Pre-checks
          href: dapool_prechk-v01_afdhs.qmd
        - text: Bangladesh DHS Pre-checks
          href: dapool_prechk-v01_bddhs.qmd
        - text: India DHS Pre-checks
          href: dapool_prechk-v01_iadhs.qmd
        - text: Maldives DHS Pre-checks
          href: dapool_prechk-v01_mvdhs.qmd
        - text: Nepal DHS Pre-checks
          href: dapool_prechk-v01_npdhs.qmd
        - text: Pakistan DHS Pre-checks
          href: dapool_prechk-v01_pkdhs.qmd
      - text: Pooled Datadicts
        href: dadict_postpool.qmd
      - text: Prelim Data Analysis
        menu:
        - text: Afghanistan DHS Prelim
          href: daanal_prelim-v01_afdhs.qmd
        - text: Bangladesh DHS Prelim
          href: daanal_prelim-v01_bddhs.qmd
        - text: India DHS Prelim
          href: daanal_prelim-v01_iadhs.qmd  
        - text: Maldives DHS Prelim
          href: daanal_prelim-v01_mvdhs.qmd
        - text: Nepal DHS Prelim
          href: daanal_prelim-v01_npdhs.qmd
        - text: Pakistan DHS Prelim
          href: daanal_prelim-v01_pkdhs.qmd  
  sidebar: 
    style: docked
    background: none
    tools: 
      - icon: github
        href: https://github.com/ronakpaulpc/sasiadhs_webdocs
      - icon: linkedin
        href: https://www.linkedin.com/in/ronak-paul-16462014a/
      - icon: twitter
        href: https://x.com/that_ronak
      - icon: bluesky
        href: https://bsky.app/profile/ronakpaul.bsky.social
    collapse-level: 1
    contents: 
      - section: "Full Datadicts"
        contents: 
          - text: Afghanistan DHS Dictionary
            href: dadict_afdhs.qmd
          - text: Bangladesh DHS Dictionary
            href: dadict_bddhs.qmd
          - text: India DHS Dictionary
            href: dadict_iadhs.qmd
          - text: Maldives DHS Dictionary
            href: dadict_mvdhs.qmd            
          - text: Nepal DHS Dictionary
            href: dadict_npdhs.qmd
          - text: Pakistan DHS Dictionary
            href: dadict_pkdhs.qmd
      - text: Variable Checklist
        href: davars_checklist.qmd
      - section: "Datapool Pre-checks"
        contents:
          - text: Afghanistan DHS Pre-checks
            href: dapool_prechk-v01_afdhs.qmd
          - text: Bangladesh DHS Pre-checks
            href: dapool_prechk-v01_bddhs.qmd
          - text: India DHS Pre-checks
            href: dapool_prechk-v01_iadhs.qmd
          - text: Maldives DHS Pre-checks
            href: dapool_prechk-v01_mvdhs.qmd
          - text: Nepal DHS Pre-checks
            href: dapool_prechk-v01_npdhs.qmd
          - text: Pakistan DHS Pre-checks
            href: dapool_prechk-v01_pkdhs.qmd
      - text: Pooled Datadicts
        href: dadict_postpool.qmd
      - section: "Prelim Data Analysis"
        contents:
          - text: Afghanistan DHS Prelim
            href: daanal_prelim-v01_afdhs.qmd
          - text: Bangladesh DHS Prelim
            href: daanal_prelim-v01_bddhs.qmd
          - text: India DHS Prelim
            href: daanal_prelim-v01_iadhs.qmd  
          - text: Maldives DHS Prelim
            href: daanal_prelim-v01_mvdhs.qmd
          - text: Nepal DHS Prelim
            href: daanal_prelim-v01_npdhs.qmd
          - text: Pakistan DHS Prelim
            href: daanal_prelim-v01_pkdhs.qmd  

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    toc-expand: 2
    execute:
      warning: false

editor: visual


